### ISSUE TITLE
Extracting the structural API of data handled by AurionChat

### ISSUE THREAD

**Issue by burdoto** [Mineaurion/AurionChat#39]
Hi there;

First of all dont feel bad by the amount of issues and PRs that I open; take your time!
Since I already created the [Discord Link Bot for AurionChat](https://github.com/Mineaurion/Aurionchat/pull/36), in which I had to hand-write code for compatibility to AurionChat; and also am working on [another Project that would implement remote transfer of Minecraft-related data](https://github.com/comroid-git/mc-server-hub), I would like to create a specialized API package for handling such data transfer with (not only) RabbitMQ transfer in mind.

My project not only transfers chat data, but also other [player events](https://github.com/comroid-git/mc-server-hub/blob/main/src/api/main/java/org/comroid/mcsd/api/dto/PlayerEvent.java), such as join/leave as well as death messages (with upcoming custom death message support), and possibly also other related information.

I think both this and my other project would both profit of such a library and a standardized way of communicating and transferring data with each other.

**Comment by Yann151924** [comment]
I don't know if it's enough, tell if you need more stuff in the package :)

In the package i add RabbitMQMessage class in a new module to be used in other java project and i publish it via gh action so you can use it in your project and i will use it in [Aurionchat-Automessage](https://github.com/mineaurion/aurionchat-automessage)

**Comment by Yann151924** [comment]
https://github.com/Mineaurion/Aurionchat/packages/2079063

☝️ I did not test it but for one class in it, i think it's ok :D

**Comment by burdoto** [comment]
Having this stored on github is a good idea, although I think the API package should be a bit more in-depth, as it should contain kyori dependencies and wrapper methods for correctly handing packet data; since that is stored as a serialized String inside JSON.

Also, it should contain parse and display methods for the packets themselves; such as `toString()` for PlayerEvent related things and Components.
Also, I noticed that AurionChat published messages as subcomponents of one empty text component; which isn't ideal in terms of dataflow.

Since utility dependencies like the kyori libraries differ between platforms; it might be desirable to introduce a custom, own implementation of a `Message` and/or `Component` class for data transfer.

If you ask me, the only place where you depend on kyori and gson (and maybe other applicable) should be the api package, and making the dependencies transient to the end implementation using gradle's `api` notation inside a `dependencies` block.
This way, the risk of bugs due to version mismatch in third-party projects can be minimized.
I can prepare a PR to make these adjustments if desired.

**Comment by Yann151924** [comment]
I made a quick stuff to expose only the class responsible for the message but we can iterate on this for sure to expand it. I don't know if i'll have the time today but in the next days surely.

**Comment by burdoto** [comment]
I already posted a proposal for the API in #43 for you to check out. As always, take your time! :)

**Comment by burdoto** [comment]
I realized there's an issue with using GitHub Packages for the library; as it requires authentication even for public packages for whatever reason.
No need to work on a quick fix; I will put it up on `https://maven.comroid.org`.
It can be imported with
```groovy
repositories {
    maven { url = 'https://maven.comroid.org' }
}

dependencies {
     implementation 'com.mineaurion:api:SNAPSHOT'
}
```

**Comment by Yann151924** [comment]
https://github.com/Mineaurion/Aurionchat/pull/55 i don't think it this pr solve all, but i close the issue. If we need to add some feature we will make other issue to list what needed
