### ISSUE TITLE
Wildcards in Channel Names

### ISSUE THREAD

**Issue by burdoto** [Mineaurion/AurionChat#42]
If channel names would be handled by a RabbitMQ `topic` type exchange instead of `fanout` type and used as the routing key, there would be automatic support for both the current channel system (exact match) as well as supporting RabbitMQ wildcards.

**Comment by Yann151924** [comment]
In earlier version i use a topic exchange and the key was something like `aurion.chat.<channel>`, this was ok but all server connected will just listen to `aurion.chat.*` so this was like a fanout and there was not a real utility to use the topic type.

Unless there is a real usefullness to swap for this type of exchange i prefer to stick with a fanout exchange.

**Comment by burdoto** [comment]
right, thats true it would make more sense for server management if at all. this one is not feasible
